import "./globals.css";
import type { Metadata } from "next";
import { Inconsolata } from "next/font/google";
import { Google_Sans_Code } from "next/font/google";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

export const inconsolata = Inconsolata({
  subsets: ["latin"],
  variable: "--font-inconsolata",
  display: "swap",
});

export const google_sans_code = Google_Sans_Code({
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${google_sans_code.className} antialiased`}>
        <div className="max-w-5xl mx-auto">
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
